


































}  }    );      ),        ),          ],            IconButton(icon: const Icon(Icons.delete), onPressed: onDelete),            IconButton(icon: const Icon(Icons.share), onPressed: onShare),            IconButton(icon: const Icon(Icons.copy), onPressed: onCopy),          children: [          mainAxisSize: MainAxisSize.min,        trailing: Row(        subtitle: Text(item.timestamp.toLocal().toString()),        title: Text(item.content),      child: ListTile(    return Card(  Widget build(BuildContext context) {  @override  });    required this.onDelete,    required this.onShare,    required this.onCopy,    required this.item,    super.key,  const ClipboardCard({  final VoidCallback onDelete;  final VoidCallback onShare;  final VoidCallback onCopy;  final ClipboardItem item;class ClipboardCard extends StatelessWidget {import '../models/clipboard_data.dart';import 'package:flutter/material.dart';